### ISSUE TITLE
Update version of play-ws

### ISSUE THREAD

**Issue by bfil** [codacy/codacy-api-scala#1]
For some reasons, version `2.3.8` disappeared from the Play Typesafe repository.

http://mvnrepository.com/artifact/com.typesafe.play/play-ws_2.10

This makes `sbt-codacy-coverage` and any other project depending on `codacy-api-scala` unusable.

**Comment by rtfpessoa** [comment]
@mrfyda can you release a new version based on the 2.3.9?

**Comment by bfil** [comment]
You might also have issue in relation to netty-http-pipelining `1.1.2` now missing as well: https://github.com/typesafehub/netty-http-pipelining/issues/13

**Comment by bfil** [comment]
Actually, adding the resolver:

`resolvers += "Typesafe Repository" at "http://repo.typesafe.com/typesafe/releases/"`

solves the issue, it might be that I had the dependency in my ivy cache that got deleted somehow

**Comment by bfil** [comment]
I think we can close the issue, basically since I'm using a custom SBT plugin for my own projects which depend on other SBT plugins I never needed to add a custom resolver to the `plugins.sbt` file, but `sbt-codacy-coverage` required me to do so, that caused me some headaches, but adding the Typesafe resolver fixes the issue. Sorry about that.

Would still be cool to be able to use the latest version in maven central though, it should require some code changes I guess, cause when I tried to force a later version the build broke because of binary incompatibilities.
